apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
    enabled: true
    paths:
      - /path/to/your/application/logs/*.log

    output.elasticsearch:
      hosts: ["locahost:9200"]
